version: '3'
services:
  tekeisan:
    build:
      context: .
    working_dir: /home/pwn
    container_name: tekeisan
    ulimits:
      nproc: 65535
      core: 0
    ports:
        - "4000:4000"
    entrypoint: /etc/init.sh

