version: '3'
services:
  evil:
    build:
      context: .
    working_dir: /home/pwn
    container_name: evil_eval 
    ulimits:
      nproc: 65535
      core: 0
    ports:
        - "4001:4001"
    entrypoint: /etc/init.sh

